In [2]:
# 구글드라이브 마운트
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
# library 호출
import pandas as pd
import numpy as np

# 데이터 불러오기

In [9]:
df_raw = pd.read_csv("/content/drive/MyDrive/[22-2] 딥러닝개론/project/소상공인시장진흥공단_상가(상권)정보_서울_202206.csv")
df_raw.head()

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,23324279,제중건강원,NaN,D,소매,D10,건강/미용식품,D10A07,건강원,G47216,...,1156010600100410002034626,NaN,서울특별시 영등포구 영중로14길 11-17,150035,7250.0,NaN,1,NaN,126.907168,37.520613
1,24525909,민속악기사,NaN,D,소매,D04,취미/오락관련소매,D04A09,악기판매,G47593,...,1120012200101420011000227,NaN,서울특별시 성동구 용답5길 2,133849,4803.0,NaN,NaN,NaN,127.049018,37.566857
2,24715368,태평양진주,NaN,D,소매,D26,시계/귀금속소매,D26A01,시계/귀금속,G47830,...,1111015200100440000000001,금사랑투빌딩,서울특별시 종로구 서순라길 17-10,110390,3138.0,NaN,NaN,NaN,126.993530,37.571848
3,15554136,김선희꼼꼼국어교습소,NaN,R,학문/교육,R01,학원-보습교습입시,R01A01,학원-입시,P85501,...,1171011100101970003017195,NaN,서울특별시 송파구 위례성대로12길 31,138834,5640.0,NaN,2,NaN,127.121520,37.510967
4,17174175,비지트,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1165010100108540018009586,상랑의빌딩,서울특별시 서초구 동광로18길 82,137837,6572.0,NaN,1,NaN,126.991394,37.488375

# 행 선택

## 상권업종대분류명 / 중분류명

In [16]:
# 대분류명
df_raw["상권업종대분류명"].unique() # 음식
df_category_1 = df_raw[df_raw["상권업종대분류명"] == "음식"]
df_category_1.head()

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
4,17174175,비지트,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1165010100108540018009586,상랑의빌딩,서울특별시 서초구 동광로18길 82,137837,6572.0,NaN,1,NaN,126.991394,37.488375
5,17174119,쓰리에프,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1159010700101390073009536,NaN,서울특별시 동작구 동작대로27가길 12,156816,7008.0,NaN,NaN,NaN,126.980952,37.487105
6,17174040,다향,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1165010800114850004022127,NaN,서울특별시 서초구 효령로 230,137869,6709.0,NaN,1,NaN,127.009382,37.483436
7,25530299,고향생막걸리,NaN,Q,음식,Q09,유흥주점,Q09A04,민속주점,I56219,...,1168010700106150001009703,코끼리상가,서울특별시 강남구 압구정로 216,135894,6023.0,NaN,1,NaN,127.031012,37.528073
12,17163092,도전최강달인왕만두,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1174010200102170000018014,고덕그라시움,서울특별시 강동구 고덕로 353,134082,5224.0,NaN,NaN,NaN,127.159471,37.556197

In [19]:
# 중분류명
df_category_1["상권업종중분류명"].unique()

array(['한식', '유흥주점', '커피점/카페', '패스트푸드', '닭/오리요리', '중식', '양식', '제과제빵떡케익',
       '분식', '별식/퓨전요리', '기타음식업', '일식/수산물', '부페', '음식배달서비스'], dtype=object)

In [22]:
# 중분류명이 '커피점/카페', '제과제빵떡케익'인 행 drop
df_category_2 = df_category_1[(df_category_1["상권업종중분류명"] != "커피점/카페") & (df_category_1["상권업종중분류명"] != "제과제빵떡케익")]
df_category_2.head()

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
4,17174175,비지트,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1165010100108540018009586,상랑의빌딩,서울특별시 서초구 동광로18길 82,137837,6572.0,NaN,1,NaN,126.991394,37.488375
5,17174119,쓰리에프,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1159010700101390073009536,NaN,서울특별시 동작구 동작대로27가길 12,156816,7008.0,NaN,NaN,NaN,126.980952,37.487105
6,17174040,다향,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1165010800114850004022127,NaN,서울특별시 서초구 효령로 230,137869,6709.0,NaN,1,NaN,127.009382,37.483436
7,25530299,고향생막걸리,NaN,Q,음식,Q09,유흥주점,Q09A04,민속주점,I56219,...,1168010700106150001009703,코끼리상가,서울특별시 강남구 압구정로 216,135894,6023.0,NaN,1,NaN,127.031012,37.528073
12,17163092,도전최강달인왕만두,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1174010200102170000018014,고덕그라시움,서울특별시 강동구 고덕로 353,134082,5224.0,NaN,NaN,NaN,127.159471,37.556197

## 시도명 / 시군구명

In [24]:
df_category_2["시도명"].unique()    # 서울특별시
df_category_2["시군구명"].unique()  # 서대문구

array(['서초구', '동작구', '강남구', '강동구', '마포구', '송파구', '양천구', '성동구', '광진구',
       '중구', '노원구', '관악구', '종로구', '강서구', '동대문구', '강북구', '성북구', '은평구',
       '서대문구', '용산구', '중랑구', '구로구', '영등포구', '금천구', '도봉구'], dtype=object)

In [28]:
df_region = df_category_2[df_category_2["시군구명"] == "서대문구"]
df_region.head()

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
165,20604340,손가네빈대떡,NaN,Q,음식,Q01,한식,Q01A13,파전전문,I56111,...,1141011800104090051010140,NaN,서울특별시 서대문구 증가로10길 63,120100,3662.0,NaN,1,NaN,126.925257,37.579680
224,28486206,ZINO본점,본점,Q,음식,Q06,양식,Q06A01,정통양식/경양식,I56114,...,1141011300100840001032884,NaN,서울특별시 서대문구 연대동문길 45,120160,3721.0,NaN,1,NaN,126.944391,37.564409
430,21965693,플라토어학학원,NaN,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,1141011800104260000032968,연희127빌딩,서울특별시 서대문구 연희로 286,120100,3653.0,NaN,NaN,NaN,126.936436,37.582583
812,17933610,에브리키친,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1141011100100820000016029,홍제한양아파트,서울특별시 서대문구 통일로25길 30,120782,3730.0,상가,2,NaN,126.947216,37.583265
984,20663702,참숯돼지천국,NaN,Q,음식,Q01,한식,Q01A02,갈비/삼겹살,I56111,...,1141011800100090043012704,포방빌딩,서울특별시 서대문구 홍은중앙로 118,120100,3605.0,NaN,1,NaN,126.949232,37.600953

In [30]:
df_region.shape # 총 2844개 음식점

(2844, 39)

## 이름 열 만들기 (상호명 + 지점명)

In [34]:
# 인덱스 초기화
df_region.index = range(df_region.shape[0])
df_region.head()

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도,이름
0,20604340,손가네빈대떡,NaN,Q,음식,Q01,한식,Q01A13,파전전문,I56111,...,NaN,서울특별시 서대문구 증가로10길 63,120100,3662.0,NaN,1,NaN,126.925257,37.579680,손가네빈대떡
1,28486206,ZINO본점,본점,Q,음식,Q06,양식,Q06A01,정통양식/경양식,I56114,...,NaN,서울특별시 서대문구 연대동문길 45,120160,3721.0,NaN,1,NaN,126.944391,37.564409,ZINO본점
2,21965693,플라토어학학원,NaN,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,연희127빌딩,서울특별시 서대문구 연희로 286,120100,3653.0,NaN,NaN,NaN,126.936436,37.582583,플라토어학학원
3,17933610,에브리키친,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,홍제한양아파트,서울특별시 서대문구 통일로25길 30,120782,3730.0,상가,2,NaN,126.947216,37.583265,에브리키친
4,20663702,참숯돼지천국,NaN,Q,음식,Q01,한식,Q01A02,갈비/삼겹살,I56111,...,포방빌딩,서울특별시 서대문구 홍은중앙로 118,120100,3605.0,NaN,1,NaN,126.949232,37.600953,참숯돼지천국

In [43]:
# 지점명 열 결측치 빈칸으로 채우기
df_region["지점명"].fillna("", inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6392: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [46]:
# 이름 열 만들기
df_region["이름"] = df_region["상호명"] + " " + df_region["지점명"]
df_region

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도,이름
0,20604340,손가네빈대떡,,Q,음식,Q01,한식,Q01A13,파전전문,I56111,...,NaN,서울특별시 서대문구 증가로10길 63,120100,3662.0,NaN,1,NaN,126.925257,37.579680,손가네빈대떡
1,28486206,ZINO본점,본점,Q,음식,Q06,양식,Q06A01,정통양식/경양식,I56114,...,NaN,서울특별시 서대문구 연대동문길 45,120160,3721.0,NaN,1,NaN,126.944391,37.564409,ZINO본점 본점
2,21965693,플라토어학학원,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,연희127빌딩,서울특별시 서대문구 연희로 286,120100,3653.0,NaN,NaN,NaN,126.936436,37.582583,플라토어학학원
3,17933610,에브리키친,,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,홍제한양아파트,서울특별시 서대문구 통일로25길 30,120782,3730.0,상가,2,NaN,126.947216,37.583265,에브리키친
4,20663702,참숯돼지천국,,Q,음식,Q01,한식,Q01A02,갈비/삼겹살,I56111,...,포방빌딩,서울특별시 서대문구 홍은중앙로 118,120100,3605.0,NaN,1,NaN,126.949232,37.600953,참숯돼지천국
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2839,18541986,히얼,,Q,음식,Q06,양식,Q06A01,정통양식/경양식,I56114,...,NaN,서울특별시 서대문구 연세로5다길 46,120834,3787.0,NaN,NaN,NaN,126.933107,37.557162,히얼
2840,18543572,옛날통닭and포차,,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,포방빌딩,서울특별시 서대문구 홍은중앙로 118,120841,3605.0,NaN,1,NaN,126.949232,37.600953,옛날통닭and포차
2841,18543769,이로운밥상,,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,NaN,서울특별시 서대문구 연대동문길 27-6,120140,3721.0,NaN,2,NaN,126.943717,37.564042,이로운밥상
2842,18547262,장성원부대찌개뼈해장국,홍제점,Q,음식,Q01,한식,Q01A05,해장국/감자탕,I56111,...,원일아파트,서울특별시 서대문구 통일로 476,120857,3628.0,NaN,1,NaN,126.942443,37.590873,장성원부대찌개뼈해장국 홍제점
2843,18546745,신촌포가레,,Q,음식,Q10,별식/퓨전요리,Q10A08,동남아음식전문점,I56119,...,광연빌딩,서울특별시 서대문구 명물길 26,120833,3777.0,NaN,NaN,NaN,126.938236,37.557875,신촌포가레

In [48]:
# 이름 열 결측치 확인
df_region["이름"].isnull().sum()

0

In [49]:
# 행만 정제한 데이터프레임 저장
df_row_cleared = df_region
df_row_cleared.to_csv("/content/drive/MyDrive/[22-2] 딥러닝개론/project/publicdata_rowcleared.csv", sep=',')

In [54]:
# 저장한 데이터프레임 확인
df_saved = pd.read_csv("/content/drive/MyDrive/[22-2] 딥러닝개론/project/publicdata_rowcleared.csv", index_col=0)
df_saved.head()

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도,이름
0,20604340,손가네빈대떡,NaN,Q,음식,Q01,한식,Q01A13,파전전문,I56111,...,NaN,서울특별시 서대문구 증가로10길 63,120100,3662.0,NaN,1,NaN,126.925257,37.579680,손가네빈대떡
1,28486206,ZINO본점,본점,Q,음식,Q06,양식,Q06A01,정통양식/경양식,I56114,...,NaN,서울특별시 서대문구 연대동문길 45,120160,3721.0,NaN,1,NaN,126.944391,37.564409,ZINO본점 본점
2,21965693,플라토어학학원,NaN,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,연희127빌딩,서울특별시 서대문구 연희로 286,120100,3653.0,NaN,NaN,NaN,126.936436,37.582583,플라토어학학원
3,17933610,에브리키친,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,홍제한양아파트,서울특별시 서대문구 통일로25길 30,120782,3730.0,상가,2,NaN,126.947216,37.583265,에브리키친
4,20663702,참숯돼지천국,NaN,Q,음식,Q01,한식,Q01A02,갈비/삼겹살,I56111,...,포방빌딩,서울특별시 서대문구 홍은중앙로 118,120100,3605.0,NaN,1,NaN,126.949232,37.600953,참숯돼지천국

# 열 선택

In [56]:
# 전체 column 확인
df_region.columns
#columns_list = ['상가업소번호', '상호명', '지점명', '상권업종대분류코드', '상권업종대분류명', '상권업종중분류코드',
#                '상권업종중분류명', '상권업종소분류코드', '상권업종소분류명', '표준산업분류코드', '표준산업분류명', '시도코드',
#                '시도명', '시군구코드', '시군구명', '행정동코드', '행정동명', '법정동코드', '법정동명', '지번코드',
#                '대지구분코드', '대지구분명', '지번본번지', '지번부번지', '지번주소', '도로명코드', '도로명', '건물본번지',
#                '건물부번지', '건물관리번호', '건물명', '도로명주소', '구우편번호', '신우편번호', '동정보', '층정보',
#                '호정보', '경도', '위도', '이름']

Index(['상가업소번호', '상호명', '지점명', '상권업종대분류코드', '상권업종대분류명', '상권업종중분류코드',
       '상권업종중분류명', '상권업종소분류코드', '상권업종소분류명', '표준산업분류코드', '표준산업분류명', '시도코드',
       '시도명', '시군구코드', '시군구명', '행정동코드', '행정동명', '법정동코드', '법정동명', '지번코드',
       '대지구분코드', '대지구분명', '지번본번지', '지번부번지', '지번주소', '도로명코드', '도로명', '건물본번지',
       '건물부번지', '건물관리번호', '건물명', '도로명주소', '구우편번호', '신우편번호', '동정보', '층정보',
       '호정보', '경도', '위도', '이름'],
      dtype='object')

In [57]:
# 크롤링에 필요한 column: 이름, 법정동명, 시군구명
columns_select = ['이름', '상호명', '지점명', '상권업종대분류명', '상권업종중분류명', 
                  '시도명', '시군구명', '행정동명', '법정동명', '지번주소', '도로명', '도로명주소', '구우편번호', '신우편번호', '경도', '위도']

In [59]:
df_selected = df_region[columns_select]
df_selected.head()

,이름,상호명,지점명,상권업종대분류명,상권업종중분류명,시도명,시군구명,행정동명,법정동명,지번주소,도로명,도로명주소,구우편번호,신우편번호,경도,위도
0,손가네빈대떡,손가네빈대떡,,음식,한식,서울특별시,서대문구,홍은2동,홍은동,서울특별시 서대문구 홍은동 409-51,서울특별시 서대문구 증가로10길,서울특별시 서대문구 증가로10길 63,120100,3662.0,126.925257,37.579680
1,ZINO본점 본점,ZINO본점,본점,음식,양식,서울특별시,서대문구,신촌동,대신동,서울특별시 서대문구 대신동 84-1,서울특별시 서대문구 연대동문길,서울특별시 서대문구 연대동문길 45,120160,3721.0,126.944391,37.564409
2,플라토어학학원,플라토어학학원,,음식,닭/오리요리,서울특별시,서대문구,홍은2동,홍은동,서울특별시 서대문구 홍은동 426,서울특별시 서대문구 연희로,서울특별시 서대문구 연희로 286,120100,3653.0,126.936436,37.582583
3,에브리키친,에브리키친,,음식,한식,서울특별시,서대문구,홍제1동,홍제동,서울특별시 서대문구 홍제동 82,서울특별시 서대문구 통일로25길,서울특별시 서대문구 통일로25길 30,120782,3730.0,126.947216,37.583265
4,참숯돼지천국,참숯돼지천국,,음식,한식,서울특별시,서대문구,홍은1동,홍은동,서울특별시 서대문구 홍은동 9-43,서울특별시 서대문구 홍은중앙로,서울특별시 서대문구 홍은중앙로 118,120100,3605.0,126.949232,37.600953

In [60]:
# 행과 열 모두 정제한 데이터프레임 저장
df_all_cleared = df_selected
df_all_cleared.to_csv("/content/drive/MyDrive/[22-2] 딥러닝개론/project/publicdata_allcleared.csv", sep=',')

In [61]:
# 저장한 데이터프레임 확인
df_saved_2 = pd.read_csv("/content/drive/MyDrive/[22-2] 딥러닝개론/project/publicdata_allcleared.csv", index_col=0)
df_saved_2.head()

,이름,상호명,지점명,상권업종대분류명,상권업종중분류명,시도명,시군구명,행정동명,법정동명,지번주소,도로명,도로명주소,구우편번호,신우편번호,경도,위도
0,손가네빈대떡,손가네빈대떡,NaN,음식,한식,서울특별시,서대문구,홍은2동,홍은동,서울특별시 서대문구 홍은동 409-51,서울특별시 서대문구 증가로10길,서울특별시 서대문구 증가로10길 63,120100,3662.0,126.925257,37.579680
1,ZINO본점 본점,ZINO본점,본점,음식,양식,서울특별시,서대문구,신촌동,대신동,서울특별시 서대문구 대신동 84-1,서울특별시 서대문구 연대동문길,서울특별시 서대문구 연대동문길 45,120160,3721.0,126.944391,37.564409
2,플라토어학학원,플라토어학학원,NaN,음식,닭/오리요리,서울특별시,서대문구,홍은2동,홍은동,서울특별시 서대문구 홍은동 426,서울특별시 서대문구 연희로,서울특별시 서대문구 연희로 286,120100,3653.0,126.936436,37.582583
3,에브리키친,에브리키친,NaN,음식,한식,서울특별시,서대문구,홍제1동,홍제동,서울특별시 서대문구 홍제동 82,서울특별시 서대문구 통일로25길,서울특별시 서대문구 통일로25길 30,120782,3730.0,126.947216,37.583265
4,참숯돼지천국,참숯돼지천국,NaN,음식,한식,서울특별시,서대문구,홍은1동,홍은동,서울특별시 서대문구 홍은동 9-43,서울특별시 서대문구 홍은중앙로,서울특별시 서대문구 홍은중앙로 118,120100,3605.0,126.949232,37.600953

In [63]:
df_saved_2.shape

(2844, 16)